import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/FooterComponent";
import { inter } from "./fonts";
import NavbarComponent from "./components/NavbarComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={`h-screen flex flex-col justify-between bg-white ${inter.variable}`}
      >
        {/* Navbar */}
        <header className="absolute w-full z-50">
          <NavbarComponent />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
